spring:
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  h2:
    console:
      enabled: true
  http:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:h2:~/fs/db/test
  jpa:
    hibernate:
      ddl-auto: update
fs:
  storage:
    id-length: 10
    base-path: C:\\Users\\09227968\\fs\\data
    buffer-size: 10240